version: '3'

services:
  db:
    restart: always
    image: postgres:13-alpine
    container_name: postgres-container
    ports:
      - "15432:5432"
    environment:
      - DATABASE_HOST=localhost
      - POSTGRES_DB=localdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yuckyjuice
      - PGPASSWORD=yuckyjuice
    volumes:
      - ./local/data:/docker-entrypoint-initdb.d/
